### ISSUE TITLE
Bundle modder cannot patch lua files

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/Diesel-Bundle-Modder#1]
if you make a PDMOD that patches a(n) LUA file (for example patching lib/tweak_data/charactertweakdata.lua to change self.tank.SPEED_RUN to 450 in PAYDAY: The heist) when you install the PDMOD nothing will actually change. bulldozers will still run at 350cm per second.

**Comment by Luffyyy** [comment]
Use BLT.
